import { College } from '../models/College.js';

export const collegeCatalog = [
  ['Test College', 'TESTCOLLEGE', ['gmail.com']],
  ['JSS Academy of Technical Education Noida', 'JSSATEN', ['jssaten.ac.in']],
  ['JSS University Noida', 'JSSUNI', ['jssuni.edu.in']],
  ['Indian Institute of Technology Delhi', 'IITD', ['iitd.ac.in']],
  ['Delhi Technological University', 'DTU', ['dtu.ac.in']],
  ['Netaji Subhas University of Technology', 'NSUT', ['nsut.ac.in']],
  ['Bennett University', 'BENNETT', ['bennett.edu.in']],
  ['Sharda University', 'SHARDA', ['sharda.ac.in']],
  ['Galgotias University', 'GALGOTIAS', ['galgotiasuniversity.edu.in', 'galgotiasuniversity.ac.in']],
  ['Amity University Noida', 'AMITY', ['amity.edu']],
  ['Indraprastha Institute of Information Technology Delhi', 'IIITD', ['iiitd.ac.in']],
  ['Guru Gobind Singh Indraprastha University', 'GGSIPU', ['ipu.ac.in']],
  ['Jaypee Institute of Information Technology', 'JIIT', ['jiit.ac.in']],
  ['GL Bajaj Institute of Technology and Management', 'GLBITM', ['glbitm.ac.in']],
  ['Noida Institute of Engineering and Technology', 'NIET', ['niet.co.in']],
  ['ABES Engineering College', 'ABES', ['abes.ac.in']],
  ['Ajay Kumar Garg Engineering College', 'AKGEC', ['akgec.ac.in']],
  ['Greater Noida Institute of Technology', 'GNIT', ['gnit.ac.in']],
  ['IILM University Greater Noida', 'IILM', ['iilm.edu']],
  ['Shiv Nadar University', 'SNU', ['snu.edu.in']],
  ['Maharaja Agrasen Institute of Technology', 'MAIT', ['mait.ac.in']],
  ['Maharaja Surajmal Institute of Technology', 'MSIT', ['msit.in']],
  ['Bharati Vidyapeeth College of Engineering', 'BVCOE', ['bharatividyapeeth.edu']],
  ['Bharati Vidyapeeth Institute of Computer Applications and Management', 'BVICAM', ['bvicam.ac.in']],
  ['National Institute of Technology Delhi', 'NITD', ['nitdelhi.ac.in']],
  ['Jamia Millia Islamia', 'JMI', ['jmi.ac.in']],
  ['Jamia Hamdard', 'JH', ['jamiahamdard.ac.in']],
  ['Delhi Skill and Entrepreneurship University', 'DSEU', ['dseu.ac.in']],
  ['Delhi Pharmaceutical Sciences and Research University', 'DPSRU', ['dpsru.edu.in']],
  ['Indira Gandhi Delhi Technical University for Women', 'IGDTUW', ['igdtuw.ac.in']],
  ['Guru Tegh Bahadur Institute of Technology', 'GTBIT', ['gtbit.ac.in']],
  ['Maharaja Agrasen University', 'MAU', ['maharajaagrasenuniversity.in']],
  ['Fairfield Institute of Management and Technology', 'FIMT', ['fimt-ggsipu.org']],
  ['HMR Institute of Technology and Management', 'HMRITM', ['hmritm.ac.in']],
  ['Vivekananda Institute of Professional Studies', 'VIPS', ['vips.edu']],
  ['Institute of Information Technology and Management', 'IITM', ['iitmjanakpuri.com']],
  ['Tecnia Institute of Advanced Studies', 'TECNIA', ['tecnia.in']],
  ['Delhi Institute of Advanced Studies', 'DIAS', ['dias.ac.in']],
  ['Chanderprabhu Jain College of Higher Studies', 'CPJ', ['cpj.edu.in']],
  ['Jagannath International Management School', 'JIMS', ['jimsindia.org']],
  ['Rukmini Devi Institute of Advanced Studies', 'RDIAS', ['rdias.ac.in']],
  ['Lingayas Vidyapeeth', 'LINGAYAS', ['lingayasvidyapeeth.edu.in']],
  ['Manav Rachna University', 'MRU', ['manavrachna.edu.in']],
  ['Manav Rachna International Institute of Research and Studies', 'MRIIRS', ['mriu.edu.in']],
  ['YMCA University of Science and Technology', 'JCBOSEUST', ['jcboseust.ac.in']],
  ['KR Mangalam University', 'KRMU', ['krmangalam.edu.in']],
  ['Ansal University', 'ANSAL', ['sgtuniversity.ac.in']],
  ['St Andrews Institute of Technology and Management', 'SAITM', ['saitm.ac.in']],
  ['GD Goenka University', 'GDGOENKA', ['gdgoenkauniversity.com']],
  ['The NorthCap University', 'NCU', ['ncuindia.edu']],
  ['SRM University Delhi NCR', 'SRM', ['srmist.edu.in']],
  ['World College of Technology and Management', 'WCTM', ['wctmgurgaon.com']],
  ['BM Institute of Engineering and Technology', 'BMIET', ['bmiet.net']],
  ['Dronacharya College of Engineering', 'DCE', ['dronacharya.info']],
  ['KIET Group of Institutions', 'KIET', ['kiet.edu']],
  ['IMS Engineering College', 'IMSEC', ['imsec.ac.in']],
  ['RKGIT', 'RKGIT', ['rkgit.edu.in']],
  ['Birla Institute of Technology Mesra', 'BITMESRA', ['bitmesra.ac.in']]
];

export const syncCollegeCatalog = async () => Promise.all(
  collegeCatalog.map(([name, code, domains]) => College.findOneAndUpdate(
    { code },
    {
      name,
      code,
      domains,
      city: 'Delhi NCR',
      zones: [
        'library',
        'cafeteria',
        'amenities',
        'college_gate',
        'mandir_area',
        'boys_hostel',
        'girls_hostel',
        'field',
        'basketball_court',
        'badminton_court',
        'volleyball_court',
        'first_year_block',
        'amphitheatre',
        'courtyard',
        'parking',
        'placement_cell_office',
        'registrar_office'
      ],
      active: true
    },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  ))
);
